use base_rrhh;
create user if not exists 'usuariolector'@'localhost' identified by 'lector123';
grant select on base_rrhh.empleados to 'usuariolector'@'localhost' ;
grant select on base_rrhh.establecimiento to 'usuariolector'@'localhost' ;
grant select on base_rrhh.especialidad to 'usuariolector'@'localhost' ;
grant select on base_rrhh.horarios to 'usuariolector'@'localhost' ;
grant select on base_rrhh.medicos to 'usuariolector'@'localhost' ;
grant select on base_rrhh.persona to 'usuariolector'@'localhost' ;
grant select on base_rrhh.puesto to 'usuariolector'@'localhost' ;
grant select on base_rrhh.salario to 'usuariolector'@'localhost' ;
grant select on base_rrhh.vacaciones to 'usuariolector'@'localhost' ;
grant select on base_rrhh.log_persona to 'usuariolector'@'localhost' ;
grant select on base_rrhh.log_salario to 'usuariolector'@'localhost' ;
revoke delete on *.* from 'usuariolector'@'localhost' ;
show grants for 'usuariolector'@'localhost' ;
use base_rrhh;
create user if not exists 'usuario2'@'localhost' identified by 'usuario123';
grant select, insert, update on base_rrhh.empleados to 'usuario2'@'localhost';
grant select, insert, update on base_rrhh.especialidad to 'usuario2'@'localhost';
grant select, insert, update on base_rrhh.establecimiento to 'usuario2'@'localhost';
grant select, insert, update on base_rrhh.horarios to 'usuario2'@'localhost';
grant select, insert, update on base_rrhh.medicos to 'usuario2'@'localhost';
grant select, insert, update on base_rrhh.persona to 'usuario2'@'localhost';
grant select, insert, update on base_rrhh.puesto to 'usuario2'@'localhost';
grant select, insert, update on base_rrhh.salario to 'usuario2'@'localhost';
grant select, insert, update on base_rrhh.vacaciones to 'usuario2'@'localhost';
grant select, insert, update on base_rrhh.log_persona to 'usuario2'@'localhost';
grant select, insert, update on base_rrhh.log_salario to 'usuario2'@'localhost';
revoke delete on *.* from 'usuario2'@'localhost';
show grants for 'usuario2'@'localhost';
